# Generated by Django 4.0 on 2021-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('catagory', models.IntegerField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
