# Generated by Django 4.0 on 2021-12-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
