# Generated by Django 4.0 on 2021-12-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_expense_cost_expense_expence_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='income',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expence',
            field=models.FloatField(choices=[('expense', 'expense'), ('income', 'income')], default=0, null=True),
        ),
    ]
