# Generated by Django 4.0 on 2021-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_expense_income_alter_expense_expence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expence',
            field=models.CharField(choices=[('expense', 'expense'), ('income', 'income')], default=0, max_length=70, null=True),
        ),
    ]
