# Generated by Django 4.0 on 2021-12-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_expense_expence'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='income',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expence',
            field=models.FloatField(default=0, null=True),
        ),
    ]
