# Generated by Django 4.0 on 2021-12-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_expense_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='catagory',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('1', '11'), ('3', '3'), ('6', '6'), ('5', '5')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('2', '2'), ('1', '1')], default='', max_length=50),
        ),
    ]
