# Generated by Django 4.0 on 2021-12-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_expense_catagory_alter_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='catagory',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2'), ('6', '6'), ('5', '5')], default='', max_length=50),
        ),
    ]
