# Generated by Django 4.0 on 2021-12-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_expense_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='catagory',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('2', '2'), ('6', '6')], max_length=50, null=True),
        ),
    ]
